<Project>
  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Central Package Management                                           │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <UseLocalProjects>true</UseLocalProjects>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ WB Packages                                                          │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup>
    <PackageVersion Include="WB.Logging" Version="[2.0.0-preview.9, 3)" />
    <PackageVersion Include="WB.Logging.Base" Version="[1.0.0-preview.16, 2)" />
    <PackageVersion Include="WB.Logging.LogSinks.Base" Version="[1.0.0-preview.14, 2)" />
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ 3rd-Party Packages                                                   │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup>
    <PackageVersion Include="MinVer" Version="[7, 8)" />
    <PackageVersion Include="Spectre.Console" Version="[0.55.2, 1.0.0)" />
    <PackageVersion Include="Spectre.Console.Analyzer" Version="[1, 2)" />
    <PackageVersion Include="Spectre.Console.Json" Version="[0.55.2, 1.0.0)" />
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Test Packages                                                        │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup>
    <PackageVersion Include="WB.CodeAnalyzer" Version="1.0.0" />
    <PackageVersion Include="AwesomeAssertions" Version="9.4.0" />
    <PackageVersion Include="AwesomeAssertions.Analyzers" Version="9.0.8" />
    <PackageVersion Include="FakeItEasy" Version="9.0.1" />
    <PackageVersion Include="FakeItEasy.Analyzer.CSharp" Version="6.1.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.0.2" />
    <PackageVersion Include="Spectre.Console.Testing" Version="[0.57.1, 1.0.0)" />
    <PackageVersion Include="TUnit" Version="1.40.10" />
    <PackageVersion Include="Verify" Version="31.16.2" />
    <PackageVersion Include="Verify.TUnit" Version="31.16.2" />
  </ItemGroup>
</Project>