name: 🏗️ Build

on:
  workflow_call:
    inputs: 
      dotnet-version:
        required: false 
        type: string
      use-local-projects:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🗃️ Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 🔧 Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: 🔄 Restore
      run: dotnet restore /p:UseLocalProjects=${{ inputs.use-local-projects }}

    - name: 🏗️ Build
      run: dotnet build --configuration Release --no-restore /p:UseLocalProjects=${{ inputs.use-local-projects }}

    - name: 📦 Pack
      run: dotnet pack --configuration Release --no-build -o .
      if: ${{ inputs.use-local-projects == 'false' }}

    - name: ⬆️ Upload package artifact
      uses: actions/upload-artifact@v4
      if: ${{ inputs.use-local-projects == 'false' }}
      with:
        name: nuget-package
        path: "*.nupkg"
